### ISSUE TITLE
Stomp SockJS Client disconnect periodically

### ISSUE THREAD

**Issue by aminmc** [RawSanj/spring-redis-websocket#1]
Hi there,

I have a spring boot app with WebSocket configured and using Redis. When I have multiple instances of the spring boot app I've noticed that my client disconnects periodically.  Is this something you have encountered?
This is my WebSocket configuration:
[https://github.com/UKHomeOffice/borders-private-workflow-engine/blob/development/src/main/java/uk/gov/homeoffice/borders/workflow/task/TaskWebSocketConfig.java](url)

Any help would be appreciated.

**Comment by RawSanj** [comment]
Hi @aminmc, I haven't came across this probably because I never connected long enough.
Can you help me with the time period client disconnects? 
I'll look look into it if the same happens with mine.

**Comment by aminmc** [comment]
Hi there

My client gets disconnected every 60 seconds. 

Thanks

**Comment by RawSanj** [comment]
@aminmc I tested my setup, I don't face any issues. I kept my app running and sending text, didn't see any disconnect.

Check if you are using the Redis Pub/Sub correctly. 
Stomp will connect to a single instance and will continue to be connected to that instance until it is disconnected. 

So if there are 2 instances and 2 clients get connected to 2 different instances to sync messages across these instances you'd need Redis Pub/Sub.

**Comment by aminmc** [comment]
Hi there. Thanks for the update. We have a Nginx proxy in front of the multiple WebSocket servers. So my assumption is that the proxy is disconnecting the client. In terms of Redis pub/sub is there docs you can point me to?

Thanks

**Comment by RawSanj** [comment]
Hey @aminmc 

Sorry for replying late.
For Nginx config you need to enable connection to switch to WebSockets.
I have that example as well, see the https://github.com/RawSanj/spring-redis-websocket/blob/master/src/main/docker/nginx.conf file.

Redis Pub/Sub doc can be found here - https://docs.spring.io/spring-data/redis/docs/2.1.3.RELEASE/reference/html/#pubsub
