### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by tamirMoshiashvili** [RawSanj/spring-redis-websocket#2]
Hi,
After examining your code, a few questions arise:

1. In the class `AsyncConfig`, you used thread-pool of size 2, is it possible to use more?

2. Why is `Topic` in `ApplicationProperies` and when does it get initialized? I assume that the method `getChatMessage` supposed to return "/topic/chat". 

Thanks in advance

**Comment by RawSanj** [comment]
> In the class AsyncConfig, you used thread-pool of size 2, is it possible to use more?
>> Yes. You can assign more threads. The limit depends on the CPU/Memory and No. of concurrent requests you expect to handle. More Info at [Spring Task Docs](https://docs.spring.io/spring/docs/current/spring-framework-reference/integration.html#scheduling-task-executor-types).

> Why is Topic in ApplicationProperies and when does it get initialized? I assume that the method getChatMessage supposed to return "/topic/chat".
>> Topic is initiated by Spring Boot on boot-up when key-values are mapped from application.properties file. Its used for nested config. More Info at [Spring Externaliz Config - Nested Properties](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html). 
I could have avoided the topic class by moving `topic` to prefix (i.e. `raw.topic`) since there is no other property in the root level.

So this [Class](https://github.com/RawSanj/spring-redis-websocket/blob/master/src/main/java/com/github/rawsanj/config/ApplicationProperties.java) can be re-written as:

    import org.springframework.boot.context.properties.ConfigurationProperties;

    @ConfigurationProperties(prefix = "raw.topic", ignoreUnknownFields = false)
    public class ApplicationProperties {

        private String message;
        private String count;

        public String getCount() {
            return count;
        }

        public void setCount(String count) {
            this.count = count;
        }

        public String getMessage() {
            return message;
        }

        public void setMessage(String message) {
            this.message = message;
        }
    }
**Note:** I have removed Topic class and moved its properties to outer class and updated prefix from `raw` to `raw.topic`.

**Comment by RawSanj** [comment]
I hope the above answers your questions. So I'm closing this.

**Comment by tamirMoshiashvili** [comment]
Thank you for your answer
