### ISSUE TITLE
Ask about Redis on this project

### ISSUE THREAD

**Issue by HelloTo4x** [RawSanj/spring-redis-websocket#6]
Hi, i read your project. You use Redis pub sub to transfer message from sender to receiver, right, and you use Webflux with Mono and Flux to improve performance, right. Why do u use Webflux and Redis Pubsub, why don't kafka or rabbitMQ

**Comment by RawSanj** [comment]
> You use Redis pub-sub to transfer a message from sender to receiver, right
>> Yes. Redis can be used for various use-cases like in-memory cache, Key-Value store, Pub-Sub messaging, etc. More info: https://redis.io/

> you use Webflux with Mono and Flux to improve performance, right
>> Not exactly. Webflux with Mono/Flux gives the ability to write reactive code which doesn't necessarily always mean high performance. Performance would be high if you are doing I/O and in this application, we are doing HTTP/WebSocket/Pub-Sub which are all I/O calls. 
If you are doing CPU-bound tasks (say calculating squares for a list of Integers) then plain java for-loop is fastest, then java 8 Streams.forEach while Flux.subscribe() would be the slowest.
But if you are doing I/O-bound tasks (say calling third party-API) then Flux will be faster and easier to implement and parallelize the calls. More Info: https://projectreactor.io/learn and https://projectreactor.io/docs/core/release/reference/

> Why do u use Webflux and Redis Pubsub, why don't Kafka or rabbitMQ
>> Several reasons:  
>> 1. Redis has fully reactive drivers which help implement a complete reactive stack
>> 2. Redis is lightweight, fast, comparatively easy to set up, a single docker container and it is up and running
>> 3. I wanted to focus more on how to implement distributed chat applications i.e. Multiple user sessions connected to multiple different application instances and still able to send/sync messages from all instances.
>> 4. This doesn't mean we can't do the same using Kafka or RabbitMQ. At the time of writing this app, Kafka didn't have a complete reactive driver, now there is https://projectreactor.io/docs/kafka/release/reference/ 
>> 5. Also running Kafka is not as easy as Redis, No Free Cloud Instances were available while Redis small instances are free in [Heroku](https://elements.heroku.com/addons/heroku-redis) 
>> 6. If time permits, then in future I might implement Kafka. I don't have much info and experience with RabbitMQ hence I didn't use it. But you can definitely use RabbitMQ as well for Pub-Sub.

**Comment by HelloTo4x** [comment]
thank you so much

**Comment by RawSanj** [comment]
Feel free to contribute to the project and give a star if you find it helpful.

**Comment by HelloTo4x** [comment]
sure, thank u
